;; ess-mode configuration
(require-package 'ess)
(require 'ess)

(setq ess-use-auto-complete t)
(setq ess-ask-for-ess-directory t)
(setq ess-eval-visibly-p nil)
(setq ess-local-process-name "R")
(setq ess-history-directory "~/.emacs.d/ess/history")
(setq ansi-color-for-comint-mode 'filter)
(setq comint-scroll-to-bottom-on-input t)
(setq comint-scroll-to-bottom-on-output t)
(setq comint-move-point-for-output t)

(require-package 'ess-R-data-view)
(require 'ess-R-data-view)
(require-package 'ess-R-object-popup)
(require 'ess-R-object-popup)
(require-package 'ess-smart-equals)
(require 'ess-smart-equals)
(require-package 'ess-smart-underscore)
(require 'ess-smart-underscore)
(require-package 'ess-view)
(require 'ess-view)
(setq ess-view--spreadsheet-program "/Applications/Numbers.app/Contents/MacOS/Numbers")

(add-hook 'ess-mode-hook (lambda ()
                           (run-hooks 'prog-mode-hook)
                           (flycheck-mode -1)))
(define-key ess-mode-map (kbd "<C-M-return>") 'ess-eval-region-or-line-and-step)
(define-key inferior-ess-mode-map (kbd "C-c t") 'ess-R-object-popup)
(define-key ess-mode-map (kbd "C-c t") 'ess-R-object-popup)

(provide 'init-ess)
